site_name: "nREPL: A Clojure network REPL"
repo_url: https://github.com/nrepl/nREPL
edit_uri: edit/master/doc/
site_favicon: favicon.ico
copyright: "Copyright &copy; 2018 Chas Emerick, Bozhidar Batsov and nREPL contributors"
docs_dir: doc
pages:
- Home: index.md
- Installation: installation.md
- Usage: usage.md
- Design: design.md
- Built-in Ops: ops.md
- FAQ: faq.md
- Third-party Middleware: third_party_middleware.md
- Hacking on nREPL: hacking_on_nrepl.md
- Additional Resources: additional_resources.md
- About:
    - History: about/history.md
    - Team: about/team.md
    - Support: about/support.md
    - Contributing: about/contributing.md
    - Release Policy: about/release_policy.md
    - Changelog: about/changelog.md
    - License: about/license.md
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
theme: readthedocs
